### ISSUE TITLE
Support for migrations?

### ISSUE THREAD

**Issue by EPinci** [dualbios/FileBaseContext#2]
Hello there, is there any way to make FileBaseContext work with migrations?

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Relational-specific methods can only be used when the context is using a relational database provider.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```

**Comment by dualbios** [comment]
Hi, I don't think that the migration makes sense for it. Migrations need to change the structure of data. FileBaseContext is based on files and you can change the structure of the files manually before using the provider.
